### ISSUE TITLE
Some metrics are incorrect

### ISSUE THREAD

**Issue by pmouawad** [ubikingenierie/ulp-observability-plugin#68]
Comparing to Summary Report I have differences in:
- Error rate: 2.88% for SR vs 0% for plugin, error is on plugin
- Max:763ms vs 380ms for plugin, error is on plugin
- Percentiles are identical which is wrong

<img width="1557" alt="Screenshot 2023-04-08 at 15 43 51" src="https://user-images.githubusercontent.com/3127467/230724544-a3fc7d96-9e84-4f06-bfb7-4d0deb4b3f80.png">
<img width="1025" alt="Screenshot 2023-04-08 at 15 44 21" src="https://user-images.githubusercontent.com/3127467/230724548-b9b5c6ea-02f5-468a-a9b3-056df50bf24b.png">

**Comment by Liard-Thomas** [comment]
@pmouawad 
I am currently working on percentiles, and there is no way to get the exact same percentiles as the ones in the report summary.
Problem is we have to add a lot of data in micrometer (one data = one sampler call -> since there is almost always a lot of samplers calls it means a lot of memory is used for it), and when there is too much data in a micrometer registry, it "shrinks" the oldest values in means, averages, max etc... but loses some data in the process. If micrometer didn't do this, we would have a memory issue. 

Because percentiles calculation need every data it can get to be precise, the total percentiles we calculate cannot be as precise as the ones in the summary.

They will always be close, but never really the same in the plugin and report.
