### ISSUE TITLE
The 3 percentiles have the same value

### ISSUE THREAD

**Issue by pmouawad** [ubikingenierie/ulp-observability-plugin#73]
Is it due to precision ? then should be documented

<img width="476" alt="Screenshot 2023-04-08 at 16 06 16" src="https://user-images.githubusercontent.com/3127467/230725531-8ece1796-fa64-481a-bc4f-8302d19ddff2.png">

<img width="1606" alt="Screenshot 2023-04-08 at 16 07 12" src="https://user-images.githubusercontent.com/3127467/230725565-29458da3-3d6d-4330-8718-a8ee35506f2a.png">

**Comment by Liard-Thomas** [comment]
@pmouawad I can reproduce the "bug", but i don't think this is actually a bug.
The test plan you gave me has a total throughput of around 0.5 request sent per seconds.
With a log frequency of 10, it means that for every periods, every percentiles starting from +- 80% will all have the exact same value.

It can be even more confusing when you look at the total percentiles inside the blue tiles. Because they are calculated based on every values, you can have different values for 90, 95 and 99 %, while they are always the same for each period in the graphs.

It is because this time, the number of data on which it calculates the percentiles is high enough to have different values between 90, 95 and 99.
